update gh-action - use pyproject.toml for deps

diff --git a/.github/workflows/generate_active_daily.yml b/.github/workflows/generate_active_daily.yml
--- a/.github/workflows/generate_active_daily.yml
+++ b/.github/workflows/generate_active_daily.yml
@@ -27,13 +27,14 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         if [ -f pyproject.toml ]; then
         pip install $(python -c '
-        try: import tomllib
-        except ModuleNotFoundError: import tomli as tomllib
+        import tomllib
         print(" ".join(tomllib.load(open("pyproject.toml", "rb"))["project"]["dependencies"]))
         ')
+        else
+        echo "Missing pyproject.toml"
+        exit 1
         fi
     - name: Generate Active Daily
       run: |
